project:
  type: website
  output-dir: docs

website:
  title: "Katherine R. McLaughlin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: publication.qmd
        text: Publications

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    page-layout: full



