---
title: "Publications"
---

## Refereed Publications

<ol reversed>

<li>Arntson, L., **McLaughlin, K.R.**, and Smit, E. (2024), “Factors influencing fever care-seeking for children under five years of age in The Gambia: a secondary analysis of 2019–20 DHS data.” *Malaria Journal*, 23, 124. [link]</li>

<li>**McLaughlin, K.R.**, Johnston, L.G., Japuki, X., Gexha-Bunjaku, D., Deva, E., and Handcock, M.S. (2024), “Modeling the visibility distribution for population size estimation with respondent-driven sampling,” *The Annals of Applied Statistics*, 18(1):683-703. [link]</li>

<li>Lawless, J., Diel, D.G., Wagner, B., Cummings, K.J., Meredith, G., Parrilla, L., Plocharczyk, E., Lawlis, R., Hillson, S., Dalziel, B.D., Bethel, J., Lubchenco, J., **McLaughlin, K.R.**, Haggerty, R., Higley, K., Nieto, F.J., Radniecki, T.S., Kelly, C., Sanders, J., and Cazer, C.L. (2024), “Representative Public Health Surveys Pose Several Challenges: Lessons Learned Across Eight Communities During the COVID-19 Pandemic.” *American Journal of Preventative Medicine Focus*, 3(2):100198. [link]</li>

<li>Phatak, G., Johnston, L.G., Khoudri, I., Rhilani, H.E., Kettani, A.E., and **McLaughlin, K.R.** (2023), “Trends and factors affecting knowledge of and stigma and violence towards female sex workers in Morocco.” *International Journal of Behavioral Medicine*. [link]</li>

<li>Gamble, L.J., Johnston, L.G., Pham, P., Vinck, P., and **McLaughlin, K.R.** (2023), “Estimating the size of clustered hidden populations.” *Journal of Survey Statistics and Methodology*, 11(5): 1155–1180. [link]</li>

<li>Kim, B., Johnston, L.G., Grigoryan, T., Papoyan, A., Grigoryan, S., and **McLaughlin, K.R.** (2023), “Estimating the size of hidden populations using capture-recapture successive sampling population size estimation in Armenia.” *Biometrical Journal*, 65(5):2200136. [link]</li>

<li>Layton, B., Kaya, D., Kelly, C., Williamson, K., Alegre, D., Bachhuber, S., Banwarth, P., Bethel, J., Carter, K., Dalziel, B., Dasenko, M., Geniza M., George, A., Girard, A.-M., Haggerty, R., Higley, K., Hynes, D., Lubchenco, J., **McLaughlin, K.R.**, Nieto, F.J., Noakes, A., Peterson, M., Piemonti, A., Sanders, J., Tyler, B., and Radniecki, T. (2022), “Evaluation of a wastewater-based epidemiological approach to estimate the prevalence of SARS-CoV-2 infections and the detection of viral variants in disparate Oregon communities at city and neighborhood scales.” *Environmental Health Perspectives*, 130(6):067010. [link]</li>

<li>Skinkis, P.A. and **McLaughlin, K.R.** (2022), “Pinot noir crop estimation method allows growers to estimate yields earlier than lag phase,” *Catalyst: Discovery into Practice*, 6(1):30-37. [link]</li>

<li>**McLaughlin, K.R.** (2022), “A Bayesian framework for modeling the preferential recruitment process in respondent-driven sampling,” *Statistical Modelling*, 22(3):153-174. [link]</li>

<li>Johnston, L.G., **McLaughlin, K.R.**, Gios, L., Cordioli, M., Staneková, D.V., Blondeel, K., Toskin, I., Mirandola, M., and the SIALON II Network (2021), “Populations size estimations using SS-PSE among men who have sex with men in four European cities: How many MSM are living with HIV?” *European Journal of Public Health*, 31(6):1129-1136. [link]</li>

<li>Hagerty, C.H., **McLaughlin, K.R.**, Kroese, D.R., and Lutcher, L.K. (2021), “Phosphorus supply does not affect Fusarium crown rot of winter wheat,” *PhytoFrontiers*, 1(4):354-358. [Editor’s Pick] [link]</li>

<li>Arismendi, I., **McLaughlin, K.R.**, and Penaluna, B.E. (2021), “The U.S. academic fisheries co-authorship network under the lens of diversity and inclusion,” *Fisheries*, 46(8):372-382. [Featured Article] [link]</li>

<li>Hagerty, C.H., Lutcher, L.K., **McLaughlin, K.R.**, Hayes, P., Garland-Campbell, K., Paulitz, T., Graebner, R.C., and Kroese, D.R. (2021), “Reaction of winter wheat and barley cultivars to Fusarium pseudograminearum-inoculated fields in the dryland Pacific Northwest, USA,” *Agrosystems, Geosciences & Environment*, 4(2):e20173. [link]</li>

<li>Scaggs, S.A., Gerkey, D., and **McLaughlin, K.R.** (2021), “Linking subsistence harvest diversity and productivity to adaptive capacity in an Alaskan food sharing network,” *American Journal of Human Biology*, 33(4):e23573. [link]</li>

<li>Yin, C., **McLaughlin, K.R.**, Paulitz, T.C., Kroese, D.R., and Hagerty, C.H. (2020), “Population dynamics of wheat root pathogens under different tillage systems in NE Oregon,” *Plant Disease*, 104:2649-2657. [link]</li>

<li>**McLaughlin, K.R.**, Johnston, L.G., Gamble, L.J., Grigoryan, T., Papoyan, A., and Grigoryan, S. (2019), “Population size estimations among hidden populations using respondent-driven sampling surveys: Case studies from Armenia,” *JMIR Public Health and Surveillance*, 5(1):e12034. [link]</li>

<li>Reeve, A.L., Skinkis, P.A., Vance, A.J., **McLaughlin, K.R.**, Tomasino, E., Lee, J., and Tarara, J.M. (2018), “Vineyard floor management and cluster thinning inconsistently affect ‘Pinot noir’ crop load, berry composition, and wine quality,” *HortScience*, 53(3):318-328. [link]</li>

<li>**McLaughlin, K.R.** and EmBree, J.D. (2018), “Empirical assessment of programs to promote collaboration: A network model approach,” *The Annals of Applied Statistics*, 12(1):654-682. [link]</li>

<li>Johnston, L.G., **McLaughlin, K.R.**, Rouhani, S.A., and Bartels, S.A. (2017), “Measuring a hidden population: A novel technique to estimate the population size of women with sexual violence related pregnancies in South Kivu Province, Democratic Republic of Congo,” *Journal of Epidemiology and Global Health*, 7(1):45-53. [link]</li>

<li>Johnston, L.G., **McLaughlin, K.R.**, El Rhilani, H., Latifi, A., Toufik, A., Bennani, A., Alami, K., Elomari, B., and Handcock, M.S. (2015), “A novel method for estimating the size of hidden populations using respondent-driven sampling data: Case examples from Morocco,” *Epidemiology*, 26(6):846-852. [link]</li>

<li>Sholtz, R.I., **McLaughlin, K.R.**, Cirillo, P.M., Petreas, M., Park, J.S., Wolff, M.S., Factor-Litvak, P., Eskenazi, B., and Cohn, B.A. (2011), “Assaying organochlorines in archived serum for a large, long-term cohort: Implications of combining assay results from multiple laboratories over time,” *Environment International*, 37(4):709-714. [link]</li>

</ol>

## Book Chapters


<ol reversed>

<li>**McLaughlin, K.R.** (2024) “Collecting Data from Networked Populations: Snowball and Respondent-Driven Sampling.” In The Handbook of Teaching Qualitative and Mixed Research Methods: A Step-by-Step Guide for Instructors, edited by A. Ruth, A. Wutich, and H.R. Bernard, 28-32. Oxford, England: Routledge.</li>

</ol>
