---
title: "Teaching"
---

## Core MS in Statistics Courses

These courses are primarily taken by students in the Statistics Department, and are required for an MS in Statistics.

- ST 552: Statistical Methods II
- ST 553: Statistical Methods III

## Core MS in Data Analytics Courses

These courses are primarily taken by students in the Statistics Department, and are required for an MS in Data Analytics. They are offered in Ecampus (fully asynchronous) format.

- ST 518D: Data Analytics

## Elective Courses

These courses are taken by a variety of students, including students in the Statistics Department and other departments, as well as on campus and Ecampus students.

- ST 431/531: Sampling Methods
- ST 431D/531D: Sampling Methods (Ecampus)
- ST 537D: Data Visualization (Ecampus)

## Service Courses

These courses are taken by students outside of the Statistics Department, often to satisfy a major requirement or for an undergraduate or graduate minor in Statistics.

- ST 411/511: Methods of Data Analysis

## Other Courses

- ST 407/507/509: Consulting Practicum
